# 应用服务 WEB 访问端口
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: 472829
#    url: jdbc:mysql://localhost:3306/example?serviceTimeZone=Asia/Shanghai
#

spring:
security:
user:
name: root
password: 472829


mybatis-plus:
mapper-locations: classpath:/mapper/*.xml
